### ISSUE TITLE
primary keys

### ISSUE THREAD

**Issue by ondrejhlavacek** [keboola/php-jsonparser#7]
určení primárního klíče u endpointu - i pro jeho děcka

```
        - 
            # PK = id + end_date, end date nutno doplnit v pluginu
            endpoint: "insights"
            scroller: none
            parser:
                method: "facebook.insights"
            dataType: "insights"
            dataField: "data"
            params:
                # eg 2015-01-01 for the first run and then incrementally from the last run
                since: "-30 days"
            primaryKeys:
                current:
                    - id
                children:
                    values:
                        current:
                            - id
                            - end_time
```
